---
title: "Assignment-4"
author: "Rogelio Cadena"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
library(ggplot2)
```

```{r}
CPL_libraries <- st_read(
  "https://data.cambridgema.gov/api/geospatial/kn2z-b6eg?method=export&format=KML")
```

```{r}
opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/cambridge_streets.osm')
```

```{r}
MA_state_plane <- "+proj=lcc +lat_1=41.71666666666667 +lat_2=42.68333333333333 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +units=m +no_defs"

cambridge_street_features <- opq(bbox = 'Cambridge MA USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

cambridge_streets <- cambridge_street_features$osm_lines %>%
  st_transform(crs = MA_state_plane)
```

```{r}
ggplot(cambridge_streets) +
  geom_sf() +
  theme_map()
```

```{r}
path_otp <- otp_dl_jar("OTP")
```

```{r}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```



```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```


```{r}
otpcon <- otp_connect()
```


