---
title: "Assignment 4"
author: "Rogelio Cadena"
date: "10/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library
```{r library}
library(osmdata)
library(opentripplanner)
library(tidyverse)
library(sf)
library(ggthemes)
library(ggspatial)
```

# Load Locations
```{r}
Chicago_Hospitals <- st_read("kmlHospitals.kml")
```
```{r}
view(Chicago_Hospitals)
```
  
# Loading Street Data
```{r}
opq(bbox = 'Chicago IL USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_xml(file = 'OTP/graphs/default/chicago_streets.osm')
```

```{r}
IL_state_plane <- "+proj=tmerc +lat_0=36.66666666666666 +lon_0=-88.33333333333333 +k=0.9999749999999999 +x_0=300000 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs"

chicago_street_features <- opq(bbox = 'Chicago IL USA') %>%
  add_osm_feature(key = 'highway') %>%
  osmdata_sf()

chicago_streets <- chicago_street_features$osm_lines %>%
  st_transform(crs = IL_state_plane)
```

# Plotting Street Data
```{r}
ggplot(chicago_streets) +
  geom_sf() +                                                                                                                                                                     
  theme_map()
```

# Set up Open Trip Planner

```{r}
path_otp <- otp_dl_jar("OTP")
```

```{r}
otp_check_java()

```


```{r}
path_data <- file.path(getwd(), "OTP")
path_otp <- paste(path_data, "otp.jar",sep = "/")

otp_build_graph(otp = path_otp, dir = path_data, memory = 1024) 
```

```{r}
otp_setup(otp = path_otp, dir = path_data, memory =1024)
```

```{r}
otpcon <- otp_connect()
```

# Create Isochrones
```{r}
iso_5min_walk <- 
  otp_isochrone(otpcon = otpcon, fromPlace = Chicago_Hospitals, 
                mode = "WALK", cutoffSec = 300) %>%
  st_transform(crs = IL_state_plane) %>%
  mutate(mode = "walk")

iso_5min_drive <- 
  otp_isochrone(otpcon = otpcon, fromPlace = Chicago_Hospitals, 
                mode = "CAR", cutoffSec = 300) %>%
  st_transform(crs = IL_state_plane) %>%
  mutate(mode = "drive")

iso_all_modes <- rbind(iso_5min_drive, iso_5min_walk)

otp_stop()

```

```{r}
right_side <- st_bbox(iso_all_modes)$xmax
left_side  <- st_bbox(iso_all_modes)$xmin
top_side <- st_bbox(iso_all_modes)$ymax
bottom_side <- st_bbox(iso_all_modes)$ymin

ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = Chicago_Hospitals) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

# Figure 1: Isochrone Map
```{r}
ggplot(iso_all_modes) +
  annotation_map_tile(zoomin = 0, type = "cartolight", progress = "none") +
  geom_sf(aes(fill = mode), alpha = 0.5) +
  geom_sf(data = Chicago_Hospitals) +
  coord_sf(xlim = c(left_side, right_side), 
           ylim = c(bottom_side, top_side), expand = FALSE) +
  scale_fill_viridis_d(name = "Area that is reachable within 5 minutes",
                       labels = c("By car")) +
  theme_map() +
  labs(caption = "Basemap Copyright OpenStreetMap contributors")
```

# Figure 2: Area Comparison
```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas, 
       aes(x = as.numeric(walk), y = as.numeric(drive))) +
  geom_point() +
  scale_x_continuous(name = 
            "Area within a ten-minute walking distance\nof a hospital\n(square km)",
            breaks = breaks <- seq(10000, 130000, by = 20000),
            labels = breaks / 1000000) +
  scale_y_continuous(name = 
            "Area within a five-minute driving distance\nof a hospital\n(square km)",
            breaks = breaks <- seq(0, 700000, by = 100000),
            labels = breaks / 1000000) +
  theme_bw()
```

# Figure 3: Bar Chart
```{r}
iso_areas <- iso_all_modes %>%
  mutate(area = st_area(iso_all_modes)) %>%
  st_set_geometry(NULL) %>%
  pivot_wider(names_from = mode, values_from = area) 

ggplot(iso_areas,
        aes(x = fromPlace, y = as.numeric(drive), fill = as.numeric(walk)/1000000))+
geom_bar(stat = "identity", width = 0.5)+
  scale_x_discrete(name = "Hospitals",
                   labels = c("Thorek\nHospital\n& Med Ctr",
                              "Methodist\nHospital\nof Chicago",
                              "Advocate\nChrist Medical\n Center",
                              "Evanston\nHospital",
                              "Gottlieb\nMemorial\nHospital",
                              "Holy\nCross\nHospital",
                              "Holy\nFamily\nHospital",
                              "Jackson\nPark\nHosp.\nFoundation",
                              "Loretto\nHospital")) +
  scale_y_continuous(name = "Area within a five-minute driving distance\nof a hospital\n(square km)",
                     breaks = breaks <- seq(0, 15000000, by = 250000),
                     labels = breaks / 1000000) +
  scale_fill_continuous(name = "Area within a\nfive-minute\nwalking distance\nof a hospital\n(square km)")+
  theme_minimal()
```