---
title: "MCI"
author: "Rogelio Cadena"
date: "03/29/2022"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(leaflet)
library(htmltools)
library(htmlwidgets)
library(raster)
library(gstat)
library(spatial)
```

# Create Map of Mexico States
```{r, message=FALSE, warning=FALSE}
mexico_states <- st_read("mexican_states.geojson", quiet = TRUE) %>%
  

leaflet(Mexico_Albers) %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addPolygons(highlightOptions = highlightOptions(fillColor = "yellow", 
                                                  fillOpacity = 1),
              label = ~admin_name, 
              weight = 1) 

  
```

## Projections
```{r}
Mexico_Albers <- "+proj=aea +lat_1=14.5 +lat_2=32.5 +lat_0=24 +lon_0=-105 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```

# Read file of peregrinacion
```{r, message=FALSE, warning=FALSE}
p_juquila <-st_read("Peregrinacicón+Virgen+de+Juquila-Miahutlan.geojson")
```


